language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: R+gbd5kSRjYxm1iQ9kks5NtqN+bILk4GaA+GR1ozcCj/+tqewoTiN1yueMEln7ddxtLYt7YkuTVFbm9ZWGyud7yMGloBfs9UpVE0bA08XJWr17cywkdKf6VX+oQoO+EBoRy3eeeMMXp9s4Jc2yrKFLDw6X9/rNj9uG8xvf28d9lqdbU4bUTzy/bLh6Il2gmxDpQijsKUtQBrN8xq7TTaHPbM5874q6WWjJfMOws0S/eYHHuCLuMsrSehpy/btfGYWN7tJDO8yKCZDxN7kciZWatHRoZA1jH+6td7PdurCVnjes+kVlq10gs2Cxdv7KpMzu5FuM25ykEp4/gXK+WaqMWKlNaGAl68PQND6HP+tGsh8e3zRnLF8KoP5IxpqxM5gIFv4cIWHP+npOLIK2fyotE9MgjsVZ7y2ZkOsEd1MKPhhlGOcD9QdrueXwZMVe1/eN10/YWmqzuKoCyZLc/hDyphSsY3fA64K2oUHJHxvIs85YVbYIkR/d8mxSJoPr3r298zQPCFriITvCutTH6Bosh28SHPLiKftexGprHx2IvP9i0t6b4mOMr03WfNkMZzmMkYSOKH7GnkpsmW4P3Kq07WuTiSXjG9cMFf2itzZdMJqaZyQcZaMx4m/MvAAfqcOBHQqOQxOMcc0osLbnkdnUAEarZHCfSV25yQDa6Ie1o=
  app: swift-disco
  on:
    repo: sdossettswift/swift_disco
  run:
      - "rake db:migrate"
