

client3 = User.create! username: "client3",full_name: "Client: June Smith", email: "client3@example.com", password: "12345678", role: "Client"
client4 = User.create! username: "client4",full_name: "Client: January Jones", email: "client4@example.com", password: "12345678", role: "Client"
client5 = User.create! username: "client5",full_name: "Client: Swift Taylor", email: "client5@example.com", password: "12345678", role: "Client"


Document.delete_all

document1 = Document.create! matter_id: 1, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 1, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 1, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 1, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 1, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 2, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 2, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 2, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 2, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 2, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 3, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 3, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 3, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 3, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 3, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 4, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 4, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 4, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 4, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 4, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 5, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 5, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 5, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 5, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 5, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 6, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 6, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 6, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 6, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 6, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 7, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 7, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 7, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 7, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 7, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
document1 = Document.create! matter_id: 8, year:"2016" , month:"06", day: "", category:"Phone Records", description:"June Phone Log", hot_doc: true, issues: "", status: "1", title:"June Phone Records"
document2 = Document.create! matter_id: 8, year:"2016" , month:"06", day: "", category:"Financials: Assets", description:"June Bank Statement", hot_doc: false, issues: "", status: "1", title:"June Bank Statement"
document3 = Document.create! matter_id: 8, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - MasterCard ", hot_doc: false, issues: "", status: "1", title:"June Credit Card"
document4 = Document.create! matter_id: 8, year:"2016" , month:"06", day: "", category:"Financials: Expenses", description:"June Credit Card - American Express ", hot_doc: true, issues: "", status: "1", title:"June Credit Card"
document5 = Document.create! matter_id: 8, year:"2016" , month:"06", day: "", category:"Child: Health", description:"June Medical Bills", hot_doc: true, issues: "", status: "1", title:"Johnny's Hospitalization"
